library(shiny)
library(shinydashboard)
library(shinyBS)
library(leaflet)
library(shinyWidgets)

####################################################################
header <- dashboardHeader(title = "Pronóstico por planta",
                          dropdownMenuOutput("notifications") )

####################################################################
sidebar <- dashboardSidebar(
  
  sidebarMenu(
    
    menuItem(" 1. Angostura"     , tabName    = "ANG" , icon = icon("globe") ,
                                   badgeLabel = "ANG" , badgeColor = "red")         ,
    h1()                                                                        ,
    menuItem(" 2. Arenal"        , tabName    = "ARE" , icon = icon("globe") ,
                                   badgeLabel = "ARE" , badgeColor = "yellow")      ,
    h1()                                                                        ,
    menuItem(" 3. Cachí"         , tabName    = "CAC" , icon = icon("globe") ,
                                   badgeLabel = "CAC" , badgeColor = "aqua")        ,
    h1()                                                                        ,
    menuItem(" 4. Cariblanco"    , tabName    = "CAR" , icon = icon("globe") ,
                                   badgeLabel = "CAR" , badgeColor = "blue")        ,
    h1()                                                                        ,
    menuItem(" 5. Peñas Blancas" , tabName    = "PBL" , icon = icon("globe") ,
                                   badgeLabel = "PBL" , badgeColor = "light-blue")  ,
    h1()                                                                        ,
    menuItem(" 6. Pirrís"        , tabName    = "PIR" , icon = icon("globe") ,
                                   badgeLabel = "PIR" , badgeColor = "green")       ,
    h1()                                                                        ,
    menuItem(" 7. Reventazón"    , tabName    = "REV" , icon = icon("globe") ,
                                   badgeLabel = "REV" , badgeColor = "fuchsia")     ,
    h1()                                                                        ,
    menuItem(" 8. Río Macho"     , tabName    = "RMC" , icon = icon("globe") ,
                                   badgeLabel = "RMC" , badgeColor = "olive")       ,
    h1()                                                                        ,
    menuItem(" 9. Toro 1"        , tabName    = "TO1" , icon = icon("globe") ,
                                   badgeLabel = "TO1" , badgeColor = "lime")        ,
    h1()                                                                        ,
    menuItem("10. Toro 2"        , tabName    = "TO2" , icon = icon("globe") ,
                                   badgeLabel = "TO2" , badgeColor = "orange")      ,
    h1()                                                                        ,
    menuItem("11. V. Garita"     , tabName    = "VGA" , icon = icon("globe") ,
                                   badgeLabel = "VGA" , badgeColor = "purple")      ,
    h1()                                                                        ,
    menuItem("12. Precipitación" , tabName    = "PRE" , icon = icon("globe") ,
                                   badgeLabel = "PRE" , badgeColor = "maroon") 
             )
             )

####################################################################
body <- dashboardBody(
  
  setBackgroundColor(color = "coral", shinydashboard = TRUE),  

  tabItems(
    
    tabItem(tabName = "ANG",
            column(12, offset = 0, infoBox(width = 2, "Angostura", "(-83.64, 9.95)" ,
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                            strong("ANGOSTURA: Potencia y Ubicación",
                            style = "color:black; font-size: 16px;") )), h1(),
            column( 5, offset = 5, htmlOutput("gaugeANG"))                        ,
            #htmlOutput("gaugeANG")                                                   ,  
            column( 6, offset = 3, leafletOutput("Angostura"))                        ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_ANG_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(6, tags$img(src = "Comparacion_ANG_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Comparacion_ANG_H_REGvsTUW.jpeg" , 
            alt="Comparacion", width="740", height = "370")  ) ) , hr(),
            fluidRow(column(width = 6, offset = 3,
            tags$img(src = "Lluvia_Caudal_PRESENTE_ANG.jpeg" ,                        
            alt="Comparacion", width="800", height = "400" )  ) ), hr(),
            fluidRow(column(6, tags$img(src = "Prono_Caudal_DIARIO_ANG.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Prono_Caudal_HORARIO_ANG.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ) , hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_ANG_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_ANG_H_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_ANG_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_ANG_H_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr()
            ),
    
    tabItem(tabName = "ARE",
            column(12, offset = 0, infoBox(width = 2, "Arenal"   , "(-85.00, 10.47)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("ARENAL:  Potencia y Ubicación",
                     style = "color:black; font-size: 16px;") )), h1(),  
            column( 5, offset = 5, htmlOutput("gaugeARE") )                        ,
            #htmlOutput("gaugeARE")                                                  ,  
            column( 6, offset = 3, leafletOutput("Arenal"))                           ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset=1, tags$img(src = "Comparacion_ARE_D_REGvsTUW.jpeg" , 
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset=1, tags$img(src = "Prono_Caudal_DIARIO_ARE.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "CAC",
            column(12, offset = 0, infoBox(width = 2, "Cachí"    , "(-83.81,  9.84)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("CACHÍ:   Potencia y Ubicación",
                     style = "color:black; font-size: 16px;") )), h1(),
            column( 5, offset = 5, htmlOutput("gaugeCAC") )                        ,
           # htmlOutput("gaugeCAC")                                                    ,  
            column( 6, offset = 3, leafletOutput("Cachi"))                            ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_CAC_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Comparacion_CAC_D_REGvsTUW.jpeg",
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Prono_Caudal_DIARIO_CAC.jpeg" ,
            alt="Comparacion", width="1200", height = "600")  ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_CAC_D_AJUSTADO_W.jpeg",
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_CAC_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr()
            ),
    
    tabItem(tabName = "CAR",
            column(12, offset = 0, infoBox(width = 2, "Cariblanco", "(-84.18, 10.31)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("CARIBLANCO: Potencia y Ubicación",
                     style = "color:black; font-size: 16px;") )), h1()  ,
            column( 5, offset = 5, htmlOutput("gaugeCAR") )                        ,
            #htmlOutput("gaugeCAR")                                                    ,  
            column( 6, offset = 3, leafletOutput("Cariblanco"))                       ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_CAR_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) , hr(),
            fluidRow(column(6, tags$img(src = "Comparacion_CAR_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Comparacion_CAR_H_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ),  hr(),
            fluidRow(column(width = 6, offset = 3,
            tags$img(src = "Lluvia_Caudal_PRESENTE_CAR.jpeg" ,
            alt="Comparacion", width="800", height = "400")  ) ),  hr(),
            fluidRow(column(6, tags$img(src = "Prono_Caudal_DIARIO_CAR.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Prono_Caudal_HORARIO_CAR.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ),  hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_CAR_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_CAR_H_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_CAR_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_CAR_H_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()   
            ),
    
    tabItem(tabName = "PBL",
            column(12, offset = 0, infoBox(width = 2, "Peñas Blancas", "(-84.58, 10.38)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("PEÑAS BLANCAS: Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(),   
            column( 5, offset = 5, htmlOutput("gaugePBL") )                        ,
            #htmlOutput("gaugePBL")                                                    ,  
            column( 6, offset = 3, leafletOutput("PBlancas"))                         ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_PBL_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(6, tags$img(src = "Comparacion_PBL_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Comparacion_PBL_H_REGvsTUW.jpeg" ,                         
            alt="Comparacion", width="740", height = "370")  ) ), hr(),
            fluidRow(column(width = 6, offset = 3,
            tags$img(src = "Lluvia_Caudal_PRESENTE_PBL.jpeg" ,
            alt="Comparacion", width="800", height = "400")  ) ), hr(), 
            fluidRow(column(6, tags$img(src = "Prono_Caudal_DIARIO_PBL.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Prono_Caudal_HORARIO_PBL.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_PBL_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_PBL_H_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_PBL_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_PBL_H_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "PIR",
            column(12, offset = 0, infoBox(width = 2, "Pirrís" ,  "(-84.11,  9.64)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("PIRRÍS:  Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(),
            column( 5, offset = 5, htmlOutput("gaugePIR") )                        ,
            #htmlOutput("gaugePIR")                                                    ,  
            column( 6, offset = 3, leafletOutput("Pirris"))                           ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_PIR_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Comparacion_PIR_D_REGvsTUW.jpeg",
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),      
            fluidRow(column(10, offset = 1, tags$img(src = "Prono_Caudal_DIARIO_PIR.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_PIR_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_PIR_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) ,hr()
            ),
    
    tabItem(tabName = "REV",
            column(12, offset = 0, infoBox(width = 2, "Reventazón" , "(-83.59, 10.07)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("REVENTAZÓN: Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(), 
            column( 5, offset = 5, htmlOutput("gaugeREV") )                        ,
            #htmlOutput("gaugeREV")                                                    ,  
            column( 6, offset = 3, leafletOutput("Reventazon"))                       ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_REV_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Comparacion_REV_D_REGvsTUW.jpeg",
            alt="Comparacion", width="1200", height = "600")  ) ), hr(),      
            fluidRow(column(10, offset = 1, tags$img(src = "Prono_Caudal_DIARIO_REV.jpeg" ,
            alt="Comparacion", width="1200", height = "600")  ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_REV_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_REV_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ) , hr()
            ),
    
      tabItem(tabName = "RMC",
            column(12, offset = 0, infoBox(width = 2, "Río Macho" , "(-83.85,  9.77)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("RÍO MACHO: Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(), 
            column( 5, offset = 5, htmlOutput("gaugeRMC") )                        ,
            #htmlOutput("gaugeRMC")                                                    ,
            column( 6, offset = 3, leafletOutput("RMacho"))                           ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_RMC_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(6, tags$img(src = "Comparacion_RMC_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Comparacion_RMC_H_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ), hr(), 
            fluidRow(column(width = 6, offset = 3,
            tags$img(src = "Lluvia_Caudal_PRESENTE_RMC.jpeg" ,
            alt="Comparacion", width="800", height = "400")  ) ), hr(), 
            fluidRow(column(6, tags$img(src = "Prono_Caudal_DIARIO_RMC.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Prono_Caudal_HORARIO_RMC.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_RMC_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_RMC_H_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_RMC_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_RMC_H_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "TO1",
            column(12, offset = 0, infoBox(width = 2, "Toro 1" , "(-84.28, 10.24)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("TORO 1:  Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(),
            column( 5, offset = 5, htmlOutput("gaugeTO1") )                        ,
            #htmlOutput("gaugeTO1")                                                    ,  
            column( 6, offset = 3, leafletOutput("Toro1"))                            ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_TO1_FINAL.jpeg" ,
             alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            fluidRow(column(6, tags$img(src = "Comparacion_TO1_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Comparacion_TO1_H_REGvsTUW.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ), hr(),
            fluidRow(column(width = 6, offset = 3,
            tags$img(src = "Lluvia_Caudal_PRESENTE_TO1.jpeg" ,
            alt="Comparacion", width="800", height = "400")  ) ), hr(),
            fluidRow(column(6, tags$img(src = "Prono_Caudal_DIARIO_TO1.jpeg" ,
            alt="Comparacion", width="740", height = "370") ),
            column(6, tags$img(src = "Prono_Caudal_HORARIO_TO1.jpeg" ,
            alt="Comparacion", width="740", height = "370")  ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_TO1_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(), 
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_TO1_H_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_TO1_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_TO1_H_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "TO2",
            column(12, offset = 0, infoBox(width = 2, "Toro 2" , "(-84.26, 10.26)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("TORO 2:  Potencia y Ubicación",
                     style="color:black; font-size: 16px;"))), h1(), 
            column( 5, offset = 5, htmlOutput("gaugeTO2") )                        ,
            #htmlOutput("gaugeTO2")                                                    ,  
            column( 6, offset = 3, leafletOutput("Toro2"))                            ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_TO2_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            h1(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Comparacion_TO2_D_REGvsTUW.jpeg",
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Prono_Caudal_DIARIO_TO2.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr() ,
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_TO2_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr(),
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_TO2_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "VGA",
            column(12, offset = 0, infoBox(width = 2, "V. Garita" , "(-84.36,  9.93)",
            "longitud,   latitud", icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                    strong("VENTANAS GARITA:  Potencia y Ubicación",
                    style="color:black; font-size: 16px;"))), h1() , 
            column( 5, offset = 5, htmlOutput("gaugeVGA") )                        ,
            #htmlOutput("gaugeVGA")                                                    ,  
            column( 6, offset = 3, leafletOutput("Vgarita"))                          ,
            column(12, h4(".") )                                                      ,
            fluidRow(column(10, offset = 2,  tags$img(src = "Z_Prono_VGA_FINAL.jpeg" ,
            alt="Comparacion", width="1300", height = "650") ) ) ,hr(),
            h1(),
            fluidRow(column(10, offset = 1, tags$img(src = "Comparacion_VGA_D_REGvsTUW.jpeg" ,
            alt="Comparacion", width="1200", height = "600")  ) ), hr(),
            fluidRow(column(10, offset = 1, tags$img(src = "Prono_Caudal_DIARIO_VGA.jpeg" ,
            alt="Comparacion", width="1200", height = "600")  ) ), hr() ,
            fluidRow(column(10, offset = 1,  tags$img(src = "Pronos_VGA_D_AJUSTADO_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr() ,
            fluidRow(column(10, offset = 1,  tags$img(src = "Z_Prono_VGA_D_W.jpeg" ,
            alt="Comparacion", width="1200", height = "600") ) ), hr()
            ),
    
    tabItem(tabName = "PRE",
            column(12, offset = 0, infoBox(width = 2, "Precipitación", "[mm]",
            "Diaria y Horaria"   , icon = icon("globe"), color = "blue", fill = T) )  ,
            fluidRow(column(4, offset = 5,
                     strong("COSTA RICA: Potencia y Ubicación de Plantas",
                     style="color:black; font-size: 16px;"))), h1()                   ,
            column( 5, offset = 5, htmlOutput("gaugePRE") )                        ,
            #htmlOutput("gaugePRE")                                                    ,
            column( 6, offset = 3, leafletOutput("Plantas"))                          ,
            column(12, h4(".") )                                                      ,
            h1(),
            fluidRow(column(8, offset = 2,  tags$img(src = "Prono_Lluvia_DIARIA.jpeg" ,
            alt="Comparacion", width="1000", height = "500") ) ),
            hr(), 
            fluidRow(column(8, offset = 2,  tags$img(src = "Prono_Lluvia_HORARIA.jpeg" ,
            alt="Comparacion", width="1000", height = "500") ) ), hr()   
            )
    
            )
            )

dashboardPage(header, sidebar, body, title="Hidrología - ICE", skin = "red")
# skin = c("blue", "black","purple", "green", "red", "yellow")
